In [22]:
import numpy as np
import pandas as pd
import sklearn as sk
import scipy as sp

a = np.eye(2000,2000)
b = np.eye(2000,2000)
print(a*b)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
